# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on:
  push:
    branches:
      - develop # develop 브랜치에 직접 push될 때
  pull_request:
    types: [labeled] # PR에 라벨이 붙여질 때만

# List of jobs
jobs:
  chromatic:
    name: "Run Chromatic"
    runs-on: ubuntu-latest
    # push 이벤트이거나, PR에 chromatic 라벨이 있을 때만 실행
    if: |
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'chromatic')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: yarn
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
